version: "3.3"

services:
  build:
    build:
      context: .
      dockerfile: ./docker/build.Dockerfile
    volumes:
      - ./lib:/service/lib:consistent
      - ./types:/service/types:consistent
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_USER=test"
  test:
    build:
      context: .
      dockerfile: ./docker/test.Dockerfile
    depends_on:
    - postgres
    links:
    - postgres
    volumes:
      - ./.git:/service/.git:cached
      - ./tsconfig.json:/service/tsconfig.json:cached
      - ./jest.config.js:/service/jest.config.js:cached
      - ./src:/service/src:cached
      - /tmp/jest_runner.json:/tmp/jest_runner.json:cached
